// <auto-generated />
using System;
using InfoClients.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfoClients.Data.Migrations
{
    [DbContext(typeof(PearlContext))]
    partial class PearlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InfoClients.Data.Models.Client", b =>
                {
                    b.Property<string>("Nit")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("Address")
                        .HasMaxLength(200);

                    b.Property<decimal>("AvailableCredit");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .HasMaxLength(100);

                    b.Property<decimal>("CreditLimit");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("Phone")
                        .HasMaxLength(200);

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(100);

                    b.Property<string>("SecondName")
                        .HasMaxLength(100);

                    b.Property<string>("State")
                        .HasMaxLength(100);

                    b.Property<decimal>("VisitPercentage");

                    b.HasKey("Nit");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("InfoClients.Data.Models.SalesRepresentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("SalesRepresentative");
                });

            modelBuilder.Entity("InfoClients.Data.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientNit")
                        .IsRequired();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<decimal>("Net");

                    b.Property<int>("SalesRepresentativeId");

                    b.Property<DateTime>("VisitDate");

                    b.Property<decimal>("VisitTotal");

                    b.HasKey("Id");

                    b.HasIndex("ClientNit");

                    b.HasIndex("SalesRepresentativeId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("InfoClients.Data.Models.Visit", b =>
                {
                    b.HasOne("InfoClients.Data.Models.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientNit")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InfoClients.Data.Models.SalesRepresentative", "SalesRepresentative")
                        .WithMany()
                        .HasForeignKey("SalesRepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
